### ISSUE TITLE
embedding on facebook does not show an image 

### ISSUE THREAD

**Issue by paul2keller** [tomkr/embedr#65]
when pasting the URL from the URL bar into facebook i do not get an embedded image. i get some of the metadata (Including HTML code). see screenshot 
<img width="520" alt="screen shot 2015-09-21 at 09 14 34" src="https://cloud.githubusercontent.com/assets/5593766/9987207/9d3ed0f8-6045-11e5-9f0c-4f3e4a60df68.png">

**Comment by mzeinstra** [comment]
Fixed with https://github.com/tomkr/embedr/commit/8eafbb1df034a0f63b9ac1ef344de80e6431f318

**Comment by paul2keller** [comment]
not fixed: 

http://dev.embedr.eu/moma_66698/

gets me this: 

<img width="511" alt="screen shot 2015-09-21 at 10 50 20" src="https://cloud.githubusercontent.com/assets/5593766/9988207/d2490148-604e-11e5-94dd-815e0ee1c736.png">
